### ISSUE TITLE
Publish ctakes-clinical-pipeline to Maven Central

### ISSUE THREAD

**Issue by lewismc** [giuseppetotaro/ctakes-clinical-pipeline#1]
Hi @giuseppetotaro if it is OK with you I would like to publish this artifact on to Maven Central tomorrow.
It is a burden for me when the dependencies cannot be obtained transitively.
I'll keep this issue updated and will let you know what is going on. Nice work here Sir. :)

**Comment by giuseppetotaro** [comment]
Hi @lewismc, obviously you can publish this artifact into Maven Central.
Unfortunately, I had to use an 'internal repository' including [ctakes-assertion](http://search.maven.org/#artifactdetails%7Corg.apache.ctakes%7Cctakes-assertion%7C3.2.2%7Cjar) because it requires dependencies that still need to be uploaded to Maven Central.
Please let me know if I can do something else for this project. Thank you Sir :).

**Comment by lewismc** [comment]
Hi @giuseppetotaro NICE 
You can track it here
https://issues.sonatype.org/browse/OSSRH-17427
I'll let you know when it is finished. That is about all for now @giuseppetotaro we are using this component within ongoing development of spark-ctakes work.

**Comment by lewismc** [comment]
This issue is addressed.
The artifact can be found at https://oss.sonatype.org/content/groups/public/it/cnr/iac/ctakes-clinical-pipeline/
It will soon eb sync'd to Maven Central.
